### ISSUE TITLE
OASIS as a dependency

### ISSUE THREAD

**Issue by neuromusic** [j-friedrich/OASIS#12]
Johannes,

I'd like to make OASIS a dependency of https://github.com/AllenInstitute/neuroglia, but to do so, I need to be able to install stable versions (preferably via pip and/or conda) on Linux and Windows for Python 2.7 and 3.5+

One option would be getting it working here, then adding in the tooling to test it on windows via AppVeyor (in addition to Travis) and pushing it to PyPi when major releases happen.

Alternatively, if you were willing to contribute the core algorithm to the BSD-licensed neuroglia, I could be responsible for all of this on my end, in neuroglia. I can't do this myself because the GPL license is incompatible with mine.

Would you be willing to help make one of these happen?

Thanks,
Justin

**Comment by j-friedrich** [comment]
Hey Justin,

Excuse the delay, due to a conference followed by a short trip I am just catching up on email etc.

Whatever is easiest while still giving me some credit for OASIS. Don't have experience with making things pip installable, and the name oasis is already taken on PyPi, but am also ok with contributing the algorithm under BSD-3. Should I just fork your repo, add the oasis folder with its content (you probably don't need plotting.py) as subfolder in neuroglia and send a PR, to have it as proper contribution? I'd leave the rest, like updating setup.py for cythonizing, up to you.

Johannes

**Comment by neuromusic** [comment]
No worries at all. If you are willing to contribute under BSD-3, I can make it clear that you are a contributor to the package and make sure that the documentation for the API points to whatever publication(s) you think are relevant.

See, for example, http://nilearn.github.io/modules/generated/nilearn.decomposition.CanICA.html#nilearn.decomposition.CanICA

> Should I just fork your repo, add the oasis folder with its content (you probably don't need plotting.py) as subfolder in neuroglia and send a PR, to have it as proper contribution? I'd leave the rest, like updating setup.py for cythonizing, up to you.

This sounds like a great plan to me!!

**Comment by j-friedrich** [comment]
Ok, added it. Verified that the example still runs, at least with `ipython examples/calcium_deconvolve.py` (not sure why one has to use ipython instead python). I'll do the PR shortly.

**Comment by neuromusic** [comment]
Fantastic. Thank you!!
